language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Install VirtualBox
  - echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - curl -O https://www.virtualbox.org/download/oracle_vbox.asc
  - sudo sudo apt-key add oracle_vbox.asc
  - sudo apt-get update
  - sudo apt-get install virtualbox-4.3 dkms
  # Clone Lucerne
  - git clone https://github.com/eudoxia0/lucerne.git quicklisp/local-projects/lucerne

script:
  - cl -e '(ql:quickload :fiveam)'
       -e '(setf fiveam:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :corona-test)'

notifications:
  email:
    - eudoxiahp@gmail.com
